version: "3"
services:
  postgres:
    image: postgres
    volumes:
    - './builddb.sql:/docker-entrypoint-initdb.d/builddb.sql'
    environment:
      POSTGRES_PASSWORD: dev
    ports:
    - 5432:5432